### ISSUE TITLE
Automatically handle auth parameter if it's present

### ISSUE THREAD

**Issue by matryer** [stretchr/sdk-js#11]
`Client.init` should:
- Notice if there's an `auth` parameter in the URL
- Get it and save it in the store
- Use it, and the `user` param to get the user data, and save that too
- Refresh the page minus the `auth` and `user` parameters

**Comment by matryer** [comment]
**Note on TDDing this**

Have a method called `Stretchr.args` that gets the URL parameters.  Then you can override this in your test code to make it return what you like.  The real code should read real arguments.

NOTE: The `Stretchr.args` method might well be difficult to test.

**Comment by mazondo** [comment]
Interesting, should have read this first.  To do this TDD I used window.history.pushState to change the url params without reloading the page, then I can just make sure it sees what I want it to see, but I've only written a single high level test because this is blocked until we work out #13 

Going to leave this as is until we chat about #13, as it will change the implementation.  I like the Stretchr.args though, and pushState will let us test it.

**Comment by matryer** [comment]
Maybe I should have read this before I wrote my TDD thing… I like this approach.

**Comment by matryer** [comment]
Is this done then @mazondo ?

**Comment by mazondo** [comment]
ummm, I think?  I don't know

**Comment by mazondo** [comment]
yes, it is - kind of.  The only missing piece has been moved to #15
